{
 "title": "Pod cost & utilization metrics",
 "description": "Visualize your kubernetes costs at the pod level.",
 "tags": [
  "cost",
  "utilisation",
  "metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "costcpu", "label": "CPU", "query": "17.78" },
   { "name": "costpcpu", "label": "PE CPU", "query": "5.35" },
   { "name": "costram", "label": "RAM", "query": "2.38" },
   { "name": "costpram", "label": "PE RAM", "query": "0.72" },
   { "name": "costStorageStandard", "label": "Storage", "query": "0.044" },
   { "name": "costStorageSSD", "label": "SSD", "query": "0.187" },
   { "name": "costDiscount", "label": "Disc.", "query": "30" },
   {
    "name": "namespace",
    "label": "NS",
    "query": "query_result(sum(container_memory_working_set_bytes{namespace!=\"\"}) by (namespace))"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "query_result(sum(container_memory_working_set_bytes{namespace=\"$namespace\"}) by (pod_name))"
   }
  ]
 },
 "panels": [
  {
   "title": "Container cost and utilization analysis",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(\n sum(rate(container_cpu_usage_seconds_total{image!=\"\", namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\", cloud_google_com_gke_preemptible!=\"true\"}[1h])) by (container_name)\n * ($costcpu - ($costcpu / 100 * $costDiscount))\n) by (container_name)\n",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "sum(\n sum(rate(container_cpu_usage_seconds_total{image!=\"\", namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\", cloud_google_com_gke_preemptible=\"true\"}[1h])) by (container_name)\n or up * 0\n) by (container_name) * $costpcpu\n"
    },
    {
     "expr": "sum(\n sum(avg_over_time(container_memory_working_set_bytes{image!=\"\",namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\", cloud_google_com_gke_preemptible!=\"true\"}[1h])) by (container_name)\n * ($costram - ($costram / 100 * $costDiscount)) / 1024 / 1024 / 1024\n) by (container_name)\n",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum(\n sum(avg_over_time(container_memory_working_set_bytes{image!=\"\",namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\", cloud_google_com_gke_preemptible=\"true\"}[1h])) by (container_name)\n or up * 0\n) by (container_name) * $costpram / 1024 / 1024 / 1024\n"
    }
   ]
  },
  {
   "title": "CPU Usage vs Requested",
   "type": "graph",
   "description": "This graph attempts to show you CPU use of your application vs its requests",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}[10m])) by (container_name)",
     "legendFormat": "{{ container_name }} (usage)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", pod=\"$pod\", container!=\"POD\"}) by (container)",
     "legendFormat": "{{ container}} (request)"
    }
   ]
  },
  {
   "title": "RAM Usage vs Requested",
   "type": "graph",
   "description": "This graph attempts to show you RAM use of your application vs its requests",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (avg_over_time (container_memory_working_set_bytes{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}[1m])) by (container_name)",
     "legendFormat": "{{ container_name }} (usage)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", pod=\"$pod\", container!=\"POD\"}) by (container)",
     "legendFormat": "{{ container }} (requested)"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "description": "Traffic in and out of this pod, as a sum of its containers",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=\"$namespace\",pod_name=\"$pod\"}[10m])) by (pod_name)",
     "legendFormat": "<- in"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{namespace=\"$namespace\",pod_name=\"$pod\"}[10m])) by (pod_name)",
     "legendFormat": "-> out"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "description": "Disk read writes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_fs_writes_bytes_total{namespace=\"$namespace\",pod_name=\"$pod\"}[10m])) by (pod_name)",
     "legendFormat": "<- write"
    },
    {
     "expr": "- sum (rate (container_fs_reads_bytes_total{namespace=\"$namespace\",pod_name=\"$pod\"}[10m])) by (pod_name)",
     "legendFormat": "-> read"
    }
   ]
  }
 ]
}